// Generated by Supabase MCP for the-watch-alley project (yrzawkqcifuubtltktbk).
// Regenerate with: pnpm dlx supabase gen types typescript --project-id yrzawkqcifuubtltktbk
// Or via Hermes: Supabase MCP -> generate_typescript_types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      watches: {
        Row: {
          badge: string | null
          brand: string | null
          case_size: string | null
          condition_label: string | null
          created_at: string | null
          currency: string | null
          description: string | null
          disclosure: string | null
          display_order: number | null
          edition: string | null
          featured: boolean | null
          has_box: boolean | null
          has_papers: boolean | null
          id: string | null
          images: string[] | null
          inclusion_set: string | null
          inquiry_body: string | null
          inquiry_subject: string | null
          low_stock: boolean | null
          material: string | null
          model: string | null
          movement: string | null
          name: string | null
          price: number | null
          primary_image: string | null
          reference: string | null
          service_history: string | null
          slug: string | null
          sold_at: string | null
          sold_price: number | null
          status: string | null
          updated_at: string | null
        }
        Insert: {
          badge?: string | null
          brand?: string | null
          case_size?: string | null
          condition_label?: string | null
          created_at?: string | null
          currency?: string | null
          description?: string | null
          disclosure?: string | null
          display_order?: number | null
          edition?: string | null
          featured?: boolean | null
          has_box?: boolean | null
          has_papers?: boolean | null
          id?: string | null
          images?: string[] | null
          inclusion_set?: string | null
          inquiry_body?: string | null
          inquiry_subject?: string | null
          low_stock?: boolean | null
          material?: string | null
          model?: string | null
          movement?: string | null
          name?: string | null
          price?: number | null
          primary_image?: string | null
          reference?: string | null
          service_history?: string | null
          slug?: string | null
          sold_at?: string | null
          sold_price?: number | null
          status?: string | null
          updated_at?: string | null
        }
        Update: {
          badge?: string | null
          brand?: string | null
          case_size?: string | null
          condition_label?: string | null
          created_at?: string | null
          currency?: string | null
          description?: string | null
          disclosure?: string | null
          display_order?: number | null
          edition?: string | null
          featured?: boolean | null
          has_box?: boolean | null
          has_papers?: boolean | null
          id?: string | null
          images?: string[] | null
          inclusion_set?: string | null
          inquiry_body?: string | null
          inquiry_subject?: string | null
          low_stock?: boolean | null
          material?: string | null
          model?: string | null
          movement?: string | null
          name?: string | null
          price?: number | null
          primary_image?: string | null
          reference?: string | null
          service_history?: string | null
          slug?: string | null
          sold_at?: string | null
          sold_price?: number | null
          status?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      admin_delete_watch: { Args: { watch_id: string }; Returns: boolean }
      admin_inquiry_metrics: { Args: never; Returns: Json }
      admin_list_inquiries: {
        Args: {
          limit_count?: number
          offset_count?: number
          status_filter?: string
        }
        Returns: unknown[]
      }
      admin_mark_watch_sold: {
        Args: {
          sold_at_value: string
          sold_price_value: number
          watch_id: string
        }
        Returns: Json
      }
      admin_update_inquiry_status: {
        Args: { inquiry_id: string; new_status: string; note?: string }
        Returns: Json
      }
      admin_upsert_watch: { Args: { payload: Json }; Returns: Json }
      admin_whoami: { Args: never; Returns: Json }
      submit_inquiry: { Args: { payload: Json }; Returns: Json }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
