-- Watch Alley initial inventory seed (regenerated from public/data/watches.json on 2026-04-28).
-- IDs use the twa- prefix ("the-watch-alley", the Supabase project name).
-- Idempotent. Re-running updates rows in place.

insert into watch_alley.watches (
  id, slug, brand, model, reference, name, price, currency, status,
  condition_label, badge, movement, case_size, inclusion_set, material, edition,
  description, disclosure, primary_image, images, inquiry_subject, inquiry_body,
  sold_at, sold_price, has_box, has_papers, service_history,
  featured, low_stock, display_order
) values
('twa-001', 'omega-swatch-moonswatch-mission-to-mars', 'OMEGA × SWATCH', 'MoonSwatch — Mission to Mars', 'Mission to Mars', 'MoonSwatch — Mission to Mars', 13800, 'PHP', 'available', 'Like New 9.2/10', 'COLLAB', 'Quartz chronograph', '42 mm', 'Complete set', 'Bioceramic', 'Omega × Swatch collaboration', 'A clean Mission to Mars MoonSwatch with complete set appeal and strong collector recognizability.', 'Pre-owned condition rating should be confirmed with current daylight photos before final sale.', '/watch-assets/moonswatch.png', ARRAY['/watch-assets/moonswatch.png','/watch-assets/moonswatch-alt.png']::text[], 'Inquiry: OMEGA × SWATCH MoonSwatch — Mission to Mars', 'Hi Watch Alley, I''m interested in the MoonSwatch — Mission to Mars (₱13,800). Could you share current availability, condition photos, and included set details?', null, null, null, null, null, false, false, 0),
('twa-002', 'seiko-5-sports-srpe81k1-snowflakes', 'SEIKO', '5 Sports SRPE81K1 "Snowflakes"', 'SRPE81K1', '5 Sports SRPE81K1 "Snowflakes"', 12800, 'PHP', 'available', 'Pre-owned 8.5/10', 'LIMITED', '4R36 automatic', '42.5 mm', 'Limited edition', 'Stainless steel', 'Limited to 2,020 pieces', 'A limited Seiko 5 Sports release with the playful Snowflakes identity and accessible collector pricing.', 'Pre-owned wear should be reviewed through current daylight photos before purchase.', '/watch-assets/srpe81k1.png', ARRAY['/watch-assets/srpe81k1.png']::text[], 'Inquiry: SEIKO 5 Sports SRPE81K1 Snowflakes', 'Hi Watch Alley, I''m interested in the Seiko 5 Sports SRPE81K1 Snowflakes (₱12,800). Could you share current availability, condition photos, and set inclusions?', null, null, null, null, null, false, false, 1),
('twa-003', 'seiko-presage-sarx001-jdm-white', 'SEIKO PRESAGE', 'SARX001 JDM White', 'SARX001', 'SARX001 JDM White', 16800, 'PHP', 'available', 'Pre-owned 7.5/10', 'RARE', '6R15 automatic', '40 mm', 'Discontinued JDM reference', 'Stainless steel', 'JDM discontinued', 'A discontinued JDM Presage reference with a restrained white dial and strong enthusiast interest.', 'Condition is listed at 7.5/10; buyer should review case, bracelet, crystal, and dial photos carefully.', '/watch-assets/sarx001.png', ARRAY['/watch-assets/sarx001.png','/watch-assets/sarx001-alt.png']::text[], 'Inquiry: SEIKO PRESAGE SARX001 JDM White', 'Hi Watch Alley, I''m interested in the Seiko Presage SARX001 JDM White (₱16,800). Could you share current availability, detailed condition photos, and inclusions?', null, null, null, null, null, false, false, 2),
('twa-004', 'seiko-prospex-alpinist-whiskered-pitta-spb491j1', 'SEIKO PROSPEX', 'Alpinist "Whiskered Pitta" SPB491J1', 'SPB491J1', 'Alpinist "Whiskered Pitta" SPB491J1', 54000, 'PHP', 'available', 'Brand New 10/10', 'BRAND NEW', '6R35 automatic', '39.5 mm', 'Brand new', 'Stainless steel', '5th Philippine Limited Edition', 'The Seiko Prospex Alpinist Whiskered Pitta Philippine Limited Edition, positioned as the current featured hero piece.', 'Brand-new listing; final buyer should still confirm full set, warranty status, and current sealed/opened condition.', '/watch-assets/alpinist.png', ARRAY['/watch-assets/alpinist.png','/watch-assets/alpinist-alt.png']::text[], 'Inquiry: SEIKO PROSPEX Alpinist Whiskered Pitta SPB491J1', 'Hi Watch Alley, I''m interested in the Seiko Prospex Alpinist Whiskered Pitta SPB491J1 (₱54,000). Could you confirm availability, full set details, and warranty status?', null, null, null, null, null, false, false, 3),
('twa-005', 'seiko-jdm-brightz-ananta-saec011', 'SEIKO JDM', 'Brightz Ananta SAEC011', 'SAEC011', 'Brightz Ananta SAEC011', 32800, 'PHP', 'available', 'Pre-owned 8.8/10', 'HI-BEAT', '6R21 hi-beat automatic', '42.5 mm', 'With box', 'Stainless steel', 'JDM Brightz Ananta', 'A distinctive Seiko JDM Brightz Ananta with box, hi-beat positioning, and a more serious collector feel.', 'Movement and hi-beat description should be verified against the actual reference before publication or sale.', '/watch-assets/chatgpt-watch.png', ARRAY['/watch-assets/chatgpt-watch.png']::text[], 'Inquiry: SEIKO JDM Brightz Ananta SAEC011', 'Hi Watch Alley, I''m interested in the Seiko JDM Brightz Ananta SAEC011 (₱32,800). Could you share current availability, condition photos, and box/inclusion details?', null, null, null, null, null, false, false, 4),
('twa-006', 'seiko-presage-araigaki-sarx125-salmon-pink', 'SEIKO PRESAGE', '"Araigaki" SARX125 Salmon Pink', 'SARX125', '"Araigaki" SARX125 Salmon Pink', 42800, 'PHP', 'available', 'Brand New 10/10', 'BRAND NEW', '6R55 automatic', '40.2 mm', 'Brand new', 'Stainless steel', '72-hour reserve Presage', 'A brand-new Presage Araigaki SARX125 with salmon pink character and 72-hour power reserve appeal.', 'Brand-new listing; confirm full set, warranty status, and exact current packaging condition before sale.', '/watch-assets/watch-extra.png', ARRAY['/watch-assets/watch-extra.png']::text[], 'Inquiry: SEIKO PRESAGE Araigaki SARX125 Salmon Pink', 'Hi Watch Alley, I''m interested in the Seiko Presage Araigaki SARX125 Salmon Pink (₱42,800). Could you confirm availability, full set details, and warranty status?', null, null, null, null, null, false, false, 5),
('twa-007', 'seiko-jdm-sarg015-blue', 'SEIKO JDM', 'SARG015 Blue', 'SARG015', 'SARG015 Blue', 19800, 'PHP', 'available', 'Pre-owned 8.5/10', 'RARE', '6R15 automatic', '42 mm', 'Discontinued reference', 'Stainless steel', 'JDM discontinued', 'A discontinued Seiko JDM SARG015 in blue, targeted at collectors who like rarer everyday references.', 'Pre-owned condition rating should be supported by current daylight photos and any bracelet/case notes.', '/watch-assets/5sports-sla.png', ARRAY['/watch-assets/5sports-sla.png']::text[], 'Inquiry: SEIKO JDM SARG015 Blue', 'Hi Watch Alley, I''m interested in the Seiko JDM SARG015 Blue (₱19,800). Could you share current availability, condition photos, and inclusions?', null, null, null, null, null, false, false, 6),
('twa-008', 'seiko-presage-sarx008-hiwadairo-brown-enamel', 'SEIKO PRESAGE', 'SARX008 "Hiwadairo" Brown Enamel', 'SARX008', 'SARX008 "Hiwadairo" Brown Enamel', 34800, 'PHP', 'available', 'Pre-owned 8.8/10', 'LIMITED', '6R15 automatic', '40.5 mm', 'Limited edition', 'Stainless steel / enamel dial', 'Limited to 300 pieces', 'A limited Presage SARX008 Hiwadairo Brown Enamel with scarcity and dial craft as the main collector hooks.', 'Enamel dial, case, and crystal condition should be documented clearly in the product photo set.', '/watch-assets/sarx001-alt.png', ARRAY['/watch-assets/sarx001-alt.png','/watch-assets/sarx001.png']::text[], 'Inquiry: SEIKO PRESAGE SARX008 Hiwadairo Brown Enamel', 'Hi Watch Alley, I''m interested in the Seiko Presage SARX008 Hiwadairo Brown Enamel (₱34,800). Could you share current availability, condition photos, and limited-edition inclusions?', null, null, null, null, null, false, false, 7),
('twa-009', 'seiko-jdm-jr-west-kodama-500-chronograph', 'SEIKO JDM', 'JR West Kodama 500 Chronograph', 'JR West Kodama 500', 'JR West Kodama 500 Chronograph', 21800, 'PHP', 'available', 'Pre-owned 8.5/10', 'COLLAB', '8T63 quartz chronograph', '39.8 mm', 'Limited collaboration', 'Stainless steel', 'Limited to 5,000 pieces', 'A JR West Kodama 500 collaboration chronograph with novelty, train-culture appeal, and accessible JDM rarity.', 'Pre-owned condition, chronograph operation, and included items should be confirmed before final sale.', '/watch-assets/moonswatch-alt.png', ARRAY['/watch-assets/moonswatch-alt.png','/watch-assets/moonswatch.png']::text[], 'Inquiry: SEIKO JDM JR West Kodama 500 Chronograph', 'Hi Watch Alley, I''m interested in the Seiko JDM JR West Kodama 500 Chronograph (₱21,800). Could you share current availability, condition photos, and inclusions?', null, null, null, null, null, false, false, 8),
('twa-010', 'seiko-jdm-fast-and-furious-fire-boost-0027', 'SEIKO JDM', 'Fast & Furious Fire Boost #0027/2000', 'Fast & Furious Fire Boost', 'Fast & Furious Fire Boost #0027/2000', 24800, 'PHP', 'available', 'Like New 9.5/10', 'COLLAB', '8T63 quartz chronograph', '39.8 mm', 'Low serial limited collaboration', 'Stainless steel', 'Limited to 2,000 pieces', 'A low-serial Fast & Furious Fire Boost collaboration piece for buyers who like pop-culture Seiko collectibles.', 'Low serial and collaboration details should be verified against caseback, packaging, and paperwork photos.', '/watch-assets/alpinist-alt.png', ARRAY['/watch-assets/alpinist-alt.png','/watch-assets/alpinist.png']::text[], 'Inquiry: SEIKO JDM Fast & Furious Fire Boost #0027/2000', 'Hi Watch Alley, I''m interested in the Seiko JDM Fast & Furious Fire Boost #0027/2000 (₱24,800). Could you share current availability, condition photos, serial proof, and inclusions?', null, null, null, null, null, false, false, 9),
('twa-101', 'seiko-prospex-sla-5-sports-archive', 'SEIKO PROSPEX', '5 Sports SLA Anniversary', 'SLA Archive', '5 Sports SLA Anniversary (Sold)', 32000, 'PHP', 'sold', 'Pre-owned 9.0/10', 'SOLD', '6R35 automatic', '42 mm', 'Complete set', 'Stainless steel', 'Anniversary release', 'Sold to a long-time collector after a Viber drop. Strong tropic bracelet condition, complete set verified before turnover.', 'Archived listing — record only. Message Watch Alley if you are looking for a similar reference.', '/watch-assets/5sports-sla.png', ARRAY['/watch-assets/5sports-sla.png']::text[], 'Looking for a similar Seiko Prospex 5 Sports SLA', 'Hi Watch Alley, I missed the 5 Sports SLA Anniversary. Could you let me know if a similar reference comes through your drops?', '2026-04', 31500, null, null, null, false, false, 10),
('twa-102', 'watch-alley-curated-archive-piece', 'SEIKO', 'Curated Archive Piece', 'Archive 02', 'Curated Archive Piece (Sold)', 18500, 'PHP', 'sold', 'Pre-owned 8.5/10', 'SOLD', 'Automatic', '40 mm', 'Watch and box only', 'Stainless steel', 'Curated drop', 'Sold during a March curated drop after one DM thread. Buyer requested daylight photos and confirmed within 24 hours.', 'Archived listing — record only. Message Watch Alley for similar curated picks.', '/watch-assets/watch-extra.png', ARRAY['/watch-assets/watch-extra.png']::text[], 'Looking for a similar curated archive piece', 'Hi Watch Alley, I saw the curated archive piece in your sold archive. Could you put me on the list for a similar reference?', '2026-03', 18200, null, null, null, false, false, 11),
('twa-103', 'experimental-archive-listing', 'WATCH ALLEY', 'Experimental Archive Listing', 'Archive 03', 'Experimental Archive Listing (Sold)', 9800, 'PHP', 'sold', 'Pre-owned 8.0/10', 'SOLD', 'Quartz', '38 mm', 'Watch only', 'Stainless steel', 'Internal experimental listing', 'Internal experimental archive entry to validate the Sold Archive UX. Real listings will replace this once the workflow is live.', 'Archived placeholder — internal record only.', '/watch-assets/chatgpt-watch.png', ARRAY['/watch-assets/chatgpt-watch.png']::text[], 'Looking for archive references like this', 'Hi Watch Alley, please keep me posted when similar pieces come through your drops.', '2026-02', 9500, null, null, null, false, false, 12)
on conflict (id) do update set
  slug = excluded.slug,
  brand = excluded.brand,
  model = excluded.model,
  reference = excluded.reference,
  name = excluded.name,
  price = excluded.price,
  currency = excluded.currency,
  status = excluded.status,
  condition_label = excluded.condition_label,
  badge = excluded.badge,
  movement = excluded.movement,
  case_size = excluded.case_size,
  inclusion_set = excluded.inclusion_set,
  material = excluded.material,
  edition = excluded.edition,
  description = excluded.description,
  disclosure = excluded.disclosure,
  primary_image = excluded.primary_image,
  images = excluded.images,
  inquiry_subject = excluded.inquiry_subject,
  inquiry_body = excluded.inquiry_body,
  sold_at = excluded.sold_at,
  sold_price = excluded.sold_price,
  has_box = excluded.has_box,
  has_papers = excluded.has_papers,
  service_history = excluded.service_history,
  featured = excluded.featured,
  low_stock = excluded.low_stock,
  display_order = excluded.display_order;
