-- Vercel-like first-party referrer analytics.
-- Stores raw referrer/source rows so l.instagram.com, instagram.com,
-- lm.facebook.com, m.facebook.com, etc. remain distinct like Vercel Web Analytics.

CREATE TABLE IF NOT EXISTS visitor_referrer_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_key TEXT NOT NULL,
  source_label TEXT NOT NULL,
  uid TEXT,
  page_path TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS visitor_referrer_events_created_at_idx
  ON visitor_referrer_events (created_at DESC);
CREATE INDEX IF NOT EXISTS visitor_referrer_events_source_created_idx
  ON visitor_referrer_events (source_key, created_at DESC);

CREATE TABLE IF NOT EXISTS visitor_referrer_visitors (
  source_key TEXT NOT NULL,
  uid TEXT NOT NULL,
  source_label TEXT NOT NULL,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (source_key, uid)
);

CREATE INDEX IF NOT EXISTS visitor_referrer_visitors_last_seen_idx
  ON visitor_referrer_visitors (last_seen_at DESC);
CREATE INDEX IF NOT EXISTS visitor_referrer_visitors_source_last_seen_idx
  ON visitor_referrer_visitors (source_key, last_seen_at DESC);
